Fix Dockerfile and create directory for HTML content

diff --git a/cn b/cn
--- a/cn
+++ b/cn
@@ -10,7 +10,7 @@ if [ $(id -u) -eq 0 ]; then
 	else
 		pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
 		useradd -m -p $pass $username
-		[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
+		[ $? -eq 0 ] && echo "User has been added to system!" && mkdir -p /home/$username/public || echo "Failed to add a user!"
 	fi
 else
 	echo "Only root may add a user to the system"
