Fix scripts

diff --git a/cn b/cn
--- a/cn
+++ b/cn
@@ -1,18 +1,16 @@
 #!/bin/bash
 # Script to add a user to Linux system
 if [ $(id -u) -eq 0 ]; then
-	read -p "Enter username : " username
-	read -s -p "Enter password : " password
-	egrep "^$username" /etc/passwd >/dev/null
-	if [ $? -eq 0 ]; then
-		echo "$username exists!"
-		exit 1
-	else
-		pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
-		useradd -m -p $pass $username
-		[ $? -eq 0 ] && echo "User has been added to system!" && mkdir -p /home/$username/public || echo "Failed to add a user!"
-	fi
+  egrep "^${1}" /etc/passwd >/dev/null
+  if [ $? -eq 0 ]; then
+    echo "${1} exists!"
+    exit 1
+  else
+    pass=$(perl -e 'print crypt($ARGV[0], "password")' ${2})
+    useradd -m -p $pass ${1}
+    [ $? -eq 0 ] && echo "User has been added to system!" && mkdir -p /home/${1}/public || echo "Failed to add a user!"
+  fi
 else
-	echo "Only root may add a user to the system"
-	exit 2
+  echo "Only root may add a user to the system"
+  exit 2
 fi
